### ISSUE TITLE
Service down?

### ISSUE THREAD

**Issue by DavidKabelitz** [enupal/stripe#399] opened 2024-06-06 08:55 UTC
### Description
Website is down, js files can't be loaded. Is the Company shut down?

### Steps to reproduce

1.
2.

### Additional info

- Craft version:
- PHP version:
- Database driver & version:
- Plugin version:
- Is [SCA](https://docs.enupal.com/stripe-payments/getting-started/sca.html) and Stripe Checkout enabled?:

**Comment by vonscriptor** [comment] 2024-06-14 20:10
Hoping not! 😅 The site's SSL certificate recently expired and why it might appear as though it's not available.

**Comment by andrelopez** [comment] 2024-06-15 05:20
Thanks for reporting, the issue will be solved soon🙌🏽

**Comment by andrelopez** [comment] 2024-06-17 07:11
The issue is now fixed in the website and docs. Thank you for reporting

**Closed** 2024-06-17 07:11 UTC
